### ISSUE TITLE
NullPointerException on some calls to IntradayDataDto.toIntradayData

### ISSUE THREAD

**Issue by xmcnulty** [xmcnulty/wsb-trendies#22]
When running the app and selecting "EV" from the list, the below NullPointerException is thrown. It appears the Dto returned from the repository is null. It is unclear if it is null because the body of the response from the API is empty or if there is an issue with Gson parsing.

> java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Set java.util.Map.entrySet()' on a null object reference
        at io.xavier.topwsb.domain.mapper.IntradayDataMapperKt.toIntradayData(IntradayDataMapper.kt:55)
        at io.xavier.topwsb.data.repository.IntradayDataRepositoryImpl.getIntradayData(IntradayDataRepositoryImpl.kt:19)
        at io.xavier.topwsb.data.repository.IntradayDataRepositoryImpl$getIntradayData$1.invokeSuspend(Unknown Source:15)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@7e68393, Dispatchers.Main.immediate]

**Comment by xmcnulty** [comment]
Making the call using cURL returns the below. This error is not cured as the status code returned is 200, so no HttpException is thrown by Retrofit. There are also some tickers where a 200/OK response is returned, there is meta-data, but no time-series data. To cover both of these cases, a check for a null result or empty list will need to be checked in the repository implementation, and an exception will need to be thrown.

> StatusCode        : 200
StatusDescription : OK
Content           : {
                        "Error Message": "Invalid API call. Please retry or visit the documentation
                    (https://www.alphavantage.co/documentation/) for TIME_SERIES_INTRADAY."
                    }
RawContent        : HTTP/1.1 200 OK
                    Transfer-Encoding: chunked
                    Connection: keep-alive
                    Allow: GET, HEAD, OPTIONS
                    Vary: Cookie
                    X-Frame-Options: SAMEORIGIN
                    CF-Cache-Status: DYNAMIC
                    Server-Timing: cf-q-config;dur=4.99...
Forms             : {}
Headers           : {[Transfer-Encoding, chunked], [Connection, keep-alive], [Allow, GET, HEAD, OPTIONS], [Vary,
                    Cookie]...}
Images            : {}
InputFields       : {}
Links             : {}
ParsedHtml        : System.__ComObject
RawContentLength  : 155

**Comment by xmcnulty** [comment]
> Making the call using cURL returns the below. This error is not cured as the status code returned is 200, so no HttpException is thrown by Retrofit. There are also some tickers where a 200/OK response is returned, there is meta-data, but no time-series data. To cover both of these cases, a check for a null result or empty list will need to be checked in the repository implementation, and an exception will need to be thrown.
> 
> > StatusCode        : 200
> > StatusDescription : OK
> > Content           : {
> > "Error Message": "Invalid API call. Please retry or visit the documentation
> > (https://www.alphavantage.co/documentation/) for TIME_SERIES_INTRADAY."
> > }
> > RawContent        : HTTP/1.1 200 OK
> > Transfer-Encoding: chunked
> > Connection: keep-alive
> > Allow: GET, HEAD, OPTIONS
> > Vary: Cookie
> > X-Frame-Options: SAMEORIGIN
> > CF-Cache-Status: DYNAMIC
> > Server-Timing: cf-q-config;dur=4.99...
> > Forms             : {}
> > Headers           : {[Transfer-Encoding, chunked], [Connection, keep-alive], [Allow, GET, HEAD, OPTIONS], [Vary,
> > Cookie]...}
> > Images            : {}
> > InputFields       : {}
> > Links             : {}
> > ParsedHtml        : System.__ComObject
> > RawContentLength  : 155

The uri used for this call was: https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=EV&interval=30min&apikey=API_KEY
